#!/bin/sh
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "main" ]; then
    firebase use default > /dev/null 2>&1
elif [ "$current_branch" = "qa" ] || [ "$current_branch" = "staging" ]; then
    firebase use staging > /dev/null 2>&1
else
    firebase use staging > /dev/null 2>&1
fi

exit 0