
import { Hike } from "@/src/core/models/Hike/Hike";
import { dummyTrails } from "@/src/core/stores/dummy/dummyTrails";

export const dummyHikes: Hike[] = [
	new Hike({
		id: "hike_sample_001",
		trailId: dummyTrails[0].id,
		name: dummyTrails[0].general.name,
		date: new Date("2026-02-27T22:00:00.000Z"),
		predictedDifficulty: "Moderate",
		overallRating: 4.6,
		perceivedDifficulty: "Just Right",
		trailMaintenance: "Just Right",
		difficultyFactors: ["d2"],
		favoredFactors: ["f1", "f2"],
		review: "Great ridge walk with rewarding summit views and clear markers.",
		image: ["hikes/hike_sample_001_1.jpg"],
        completed: true,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_002",
		trailId: dummyTrails[1].id,
		name: dummyTrails[1].general.name,
		date: new Date("2026-03-01T23:30:00.000Z"),
		predictedDifficulty: "Hard",
		overallRating: 4.2,
		perceivedDifficulty: "Hard",
		trailMaintenance: "Moderate",
		difficultyFactors: ["d1", "d3"],
		favoredFactors: ["f2"],
		review: "River sections were challenging but the route remained scenic throughout.",
		image: ["hikes/hike_sample_002_1.jpg", "hikes/hike_sample_002_2.jpg"],
        completed: true,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_003",
		trailId: dummyTrails[2].id,
		name: dummyTrails[2].general.name,
		date: new Date("2026-03-02T23:15:00.000Z"),
		predictedDifficulty: "Hard",
		overallRating: 4.8,
		perceivedDifficulty: "Extreme",
		trailMaintenance: "Moderate",
		difficultyFactors: ["d1", "d2", "d3"],
		favoredFactors: ["f1", "f3"],
		review: "Technical ascent with exposed portions, but very rewarding panorama.",
		image: ["hikes/hike_sample_003_1.jpg"],
        completed: false,
        mode: 'booked',
        bookingId: 'booking_sample_001',
	}),
	new Hike({
		id: "hike_sample_004",
		trailId: dummyTrails[0].id,
		name: dummyTrails[0].general.name,
		date: new Date("2026-03-03T22:40:00.000Z"),
		predictedDifficulty: "Just Right",
		overallRating: 4.1,
		perceivedDifficulty: "Easy",
		trailMaintenance: "Easy",
		difficultyFactors: ["d1"],
		favoredFactors: ["f2", "f3"],
		review: "Good beginner route with straightforward navigation and short recovery stops.",
		image: ["hikes/hike_sample_004_1.jpg"],
        completed: true,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_005",
		trailId: dummyTrails[1].id,
		name: dummyTrails[1].general.name,
		date: new Date("2026-03-04T23:50:00.000Z"),
		predictedDifficulty: "Moderate",
		overallRating: 4.5,
		perceivedDifficulty: "Moderate",
		trailMaintenance: "Just Right",
		difficultyFactors: ["d2"],
		favoredFactors: ["f1", "f2"],
		review: "Steady incline and cool forest cover made the pace manageable.",
		image: ["hikes/hike_sample_005_1.jpg", "hikes/hike_sample_005_2.jpg"],
        completed: false,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_006",
		trailId: dummyTrails[2].id,
		name: dummyTrails[2].general.name,
		date: new Date("2026-03-05T22:20:00.000Z"),
		predictedDifficulty: "Hard",
		overallRating: 4.0,
		perceivedDifficulty: "Hard",
		trailMaintenance: "Moderate",
		difficultyFactors: ["d3"],
		favoredFactors: ["f3"],
		review: "Windy conditions near the ridge, but footing stayed reliable.",
		image: ["hikes/hike_sample_006_1.jpg"],
        completed: true,
        mode: 'booked',
        bookingId: 'booking_sample_002',
	}),
	new Hike({
		id: "hike_sample_007",
		trailId: dummyTrails[0].id,
		name: dummyTrails[0].general.name,
		date: new Date("2026-03-06T21:30:00.000Z"),
		predictedDifficulty: "Moderate",
		overallRating: 4.9,
		perceivedDifficulty: "Moderate",
		trailMaintenance: "Just Right",
		difficultyFactors: ["d2"],
		favoredFactors: ["f1", "f2", "f3"],
		review: "Excellent sunrise route with well-maintained path segments.",
		image: ["hikes/hike_sample_007_1.jpg", "hikes/hike_sample_007_2.jpg"],
        completed: false,
        mode: 'booked',
        bookingId: 'booking_sample_003',
	}),
	new Hike({
		id: "hike_sample_008",
		trailId: dummyTrails[1].id,
		name: dummyTrails[1].general.name,
		date: new Date("2026-03-07T23:10:00.000Z"),
		predictedDifficulty: "Hard",
		overallRating: 3.9,
		perceivedDifficulty: "Moderate",
		trailMaintenance: "Just Right",
		difficultyFactors: ["d1", "d2"],
		favoredFactors: ["f2", "f3"],
		review: "Humid conditions, but the waterfalls and shaded sections were worth it.",
		image: ["hikes/hike_sample_008_1.jpg"],
        completed: true,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_009",
		trailId: dummyTrails[2].id,
		name: dummyTrails[2].general.name,
		date: new Date("2026-03-08T22:45:00.000Z"),
		predictedDifficulty: "Extreme",
		overallRating: 4.4,
		perceivedDifficulty: "Hard",
		trailMaintenance: "Moderate",
		difficultyFactors: ["d1", "d3"],
		favoredFactors: ["f1", "f3"],
		review: "Demanding sections with exposed terrain but stunning cliff views.",
		image: ["hikes/hike_sample_009_1.jpg", "hikes/hike_sample_009_2.jpg"],
        completed: false,
        mode: 'direct',
	}),
	new Hike({
		id: "hike_sample_010",
		trailId: dummyTrails[0].id,
		name: dummyTrails[0].general.name,
		date: new Date("2026-03-09T22:05:00.000Z"),
		predictedDifficulty: "Just Right",
		overallRating: 4.3,
		perceivedDifficulty: "Just Right",
		trailMaintenance: "Just Right",
		difficultyFactors: ["d1"],
		favoredFactors: ["f2"],
		review: "Balanced climb with clear wayfinding and good campsite access.",
		image: ["hikes/hike_sample_010_1.jpg"],
		completed: false,
        mode: 'booked',
        bookingId: 'booking_sample_004',
	}),
];
