import { Review } from "@/src/core/models/Review/Review";
import { dummyTrails, toTrailSummary } from "@/src/core/stores/dummy/dummyTrails";
import { reviewUsers } from "@/src/core/stores/dummy/dummyUsers";

const toUserSummary = (user: (typeof reviewUsers)[number]) => ({
	id: user.id,
	username: user.username,
	firstname: user.firstname,
	lastname: user.lastname,
	email: user.email,
});

export const dummyReviews: Review[] = [
	new Review({
		id: "review_sample_001",
		createdAt: new Date("2026-03-01T08:10:00.000Z"),
		updatedAt: new Date("2026-03-01T09:00:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[3], reviewUsers[4]],
		user: toUserSummary(reviewUsers[0]),
		hike: {
			...toTrailSummary(dummyTrails[0]),
			predictedDifficulty: "Moderate",
			perceivedDifficulty: "Just Right",
			date: new Date("2026-02-27T22:00:00.000Z"),
			overallRating: 4.6,
			trailMaintenance: "Just Right",
			difficultyFactors: ["steep ascent", "slippery moss sections"],
			favoredFactors: ["sunrise viewpoint", "cool weather"],
			review: "Great ridge walk with solid trail markings and rewarding summit views.",
			image: ["reviews/review_sample_001_1.jpg"],
		},
	}),
	new Review({
		id: "review_sample_002",
		createdAt: new Date("2026-03-02T06:45:00.000Z"),
		updatedAt: new Date("2026-03-02T07:10:00.000Z"),
		likes: [reviewUsers[9], reviewUsers[8]],
		user: toUserSummary(reviewUsers[1]),
		hike: {
			...toTrailSummary(dummyTrails[1]),
			predictedDifficulty: "Hard",
			perceivedDifficulty: "Hard",
			date: new Date("2026-03-01T23:30:00.000Z"),
			overallRating: 4.2,
			trailMaintenance: "Moderate",
			difficultyFactors: ["river crossings", "long descent"],
			favoredFactors: ["waterfalls", "forest shade"],
			review: "River crossings were challenging but manageable with proper footwear.",
			image: ["reviews/review_sample_002_1.jpg", "reviews/review_sample_002_2.jpg"],
		},
	}),
	new Review({
		id: "review_sample_003",
		createdAt: new Date("2026-03-03T11:20:00.000Z"),
		updatedAt: new Date("2026-03-03T12:05:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[2], reviewUsers[3], reviewUsers[4]],
		user: toUserSummary(reviewUsers[2]),
		hike: {
			...toTrailSummary(dummyTrails[2]),
			predictedDifficulty: "Hard",
			perceivedDifficulty: "Extreme",
			date: new Date("2026-03-02T23:15:00.000Z"),
			overallRating: 4.8,
			trailMaintenance: "Moderate",
			difficultyFactors: ["rocky scramble", "exposed sections"],
			favoredFactors: ["cliff panorama", "challenging route"],
			review: "Tough but worth it. Bring gloves for the rocky sections near the top.",
			image: ["reviews/review_sample_003_1.jpg"],
		},
	}),
	new Review({
		id: "review_sample_004",
		createdAt: new Date("2026-03-04T07:55:00.000Z"),
		updatedAt: new Date("2026-03-04T08:10:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[2], reviewUsers[4], reviewUsers[5], reviewUsers[6]],
		user: toUserSummary(reviewUsers[3]),
		hike: {
			...toTrailSummary(dummyTrails[0]),
			predictedDifficulty: "Just Right",
			perceivedDifficulty: "Easy",
			date: new Date("2026-03-03T22:40:00.000Z"),
			overallRating: 4.1,
			trailMaintenance: "Easy",
			difficultyFactors: ["short muddy patch"],
			favoredFactors: ["beginner friendly route", "clear signage"],
			review: "Ideal for first-timers. Route was intuitive and not too technical.",
			image: ["reviews/review_sample_004_1.jpg"],
		},
	}),
	new Review({
		id: "review_sample_005",
		createdAt: new Date("2026-03-05T09:40:00.000Z"),
		updatedAt: new Date("2026-03-05T10:30:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[2], reviewUsers[4], reviewUsers[6], reviewUsers[8]],
		user: toUserSummary(reviewUsers[5]),
		hike: {
			...toTrailSummary(dummyTrails[1]),
			predictedDifficulty: "Moderate",
			perceivedDifficulty: "Moderate",
			date: new Date("2026-03-04T23:50:00.000Z"),
			overallRating: 4.5,
			trailMaintenance: "Just Right",
			difficultyFactors: ["humidity", "continuous incline"],
			favoredFactors: ["river pools", "bird sounds"],
			review: "Consistent climb and very scenic. Good pacing makes it enjoyable.",
			image: ["reviews/review_sample_005_1.jpg", "reviews/review_sample_005_2.jpg"],
		},
	}),
	new Review({
		id: "review_sample_006",
		createdAt: new Date("2026-03-06T05:25:00.000Z"),
		updatedAt: new Date("2026-03-06T06:02:00.000Z"),
		likes: [reviewUsers[2], reviewUsers[4], reviewUsers[6], reviewUsers[8]],
		user: toUserSummary(reviewUsers[5]),
		hike: {
			...toTrailSummary(dummyTrails[2]),
			predictedDifficulty: "Hard",
			perceivedDifficulty: "Hard",
			date: new Date("2026-03-05T22:20:00.000Z"),
			overallRating: 4.0,
			trailMaintenance: "Moderate",
			difficultyFactors: ["strong winds", "loose rocks"],
			favoredFactors: ["sunset cliff line", "wide summit area"],
			review: "Windy near the cliffs, but trail conditions were still acceptable overall.",
			image: ["reviews/review_sample_006_1.jpg"],
		},
	}),
	new Review({
		id: "review_sample_007",
		createdAt: new Date("2026-03-07T10:05:00.000Z"),
		updatedAt: new Date("2026-03-07T10:50:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[2]],
		user: toUserSummary(reviewUsers[5]),
		hike: {
			...toTrailSummary(dummyTrails[0]),
			predictedDifficulty: "Moderate",
			perceivedDifficulty: "Moderate",
			date: new Date("2026-03-06T21:30:00.000Z"),
			overallRating: 4.9,
			trailMaintenance: "Just Right",
			difficultyFactors: ["narrow ridgeline"],
			favoredFactors: ["early morning sea of clouds", "well-maintained path"],
			review: "One of the best sunrise hikes I have done this year.",
			image: ["reviews/review_sample_007_1.jpg", "reviews/review_sample_007_2.jpg"],
		},
	}),
	new Review({
		id: "review_sample_008",
		createdAt: new Date("2026-03-08T08:30:00.000Z"),
		updatedAt: new Date("2026-03-08T09:10:00.000Z"),
		likes: [reviewUsers[1], reviewUsers[2], reviewUsers[3], reviewUsers[4], reviewUsers[5]],
		user: toUserSummary(reviewUsers[7]),
		hike: {
			...toTrailSummary(dummyTrails[1]),
			predictedDifficulty: "Hard",
			perceivedDifficulty: "Moderate",
			date: new Date("2026-03-07T23:10:00.000Z"),
			overallRating: 3.9,
			trailMaintenance: "Just Right",
			difficultyFactors: ["heat", "stream crossings"],
			favoredFactors: ["waterfall basin", "friendly local guides"],
			review: "Warmer than expected, but the waterfall section made up for it.",
			image: ["reviews/review_sample_008_1.jpg"],
		},
	}),
	new Review({
		id: "review_sample_009",
		createdAt: new Date("2026-03-09T12:15:00.000Z"),
		updatedAt: new Date("2026-03-09T12:50:00.000Z"),
		likes: [reviewUsers[0], reviewUsers[1], reviewUsers[2], reviewUsers[9], reviewUsers[8]],
		user: toUserSummary(reviewUsers[8]),
		hike: {
			...toTrailSummary(dummyTrails[2]),
			predictedDifficulty: "Extreme",
			perceivedDifficulty: "Hard",
			date: new Date("2026-03-08T22:45:00.000Z"),
			overallRating: 4.4,
			trailMaintenance: "Moderate",
			difficultyFactors: ["technical rock face", "exposed ledges"],
			favoredFactors: ["dramatic cliff formations", "cool summit breeze"],
			review: "Very technical sections, but route aids made progress safer.",
			image: ["reviews/review_sample_009_1.jpg", "reviews/review_sample_009_2.jpg"],
		},
	}),
	new Review({
		id: "review_sample_010",
		createdAt: new Date("2026-03-10T04:40:00.000Z"),
		updatedAt: new Date("2026-03-10T05:05:00.000Z"),
		likes: [reviewUsers[7], reviewUsers[1], reviewUsers[3], reviewUsers[5]],
		user: toUserSummary(reviewUsers[9]),
		hike: {
			...toTrailSummary(dummyTrails[0]),
			predictedDifficulty: "Just Right",
			perceivedDifficulty: "Just Right",
			date: new Date("2026-03-09T22:05:00.000Z"),
			overallRating: 4.3,
			trailMaintenance: "Just Right",
			difficultyFactors: ["occasional slippery roots"],
			favoredFactors: ["trail markers", "summit campsite"],
			review: "Balanced climb with good rest stops. Great route for mixed groups.",
			image: ["reviews/review_sample_010_1.jpg"],
		},
	}),
];
