export const trailTemplate = {
    name: null,
    province: [],
    address: null,
    mountain: null,
    longitude: null,
    latitude: null,
    masl: null,
    start: null,
    end: null,
    length: null,
    gain: null,
    slope: null,
    obstacles: null,
    circularity: null,
    quality: null,
    hours: null,
    difficulty_points: null,
    shelter: null,
    resting: null,
    viewpoint: null,
    information_board: null,
    clean_water: null,
    river: null,
    lake: null,
    waterfall: null,
    monument: null,
    community: null,
}

export const hikingTrailTemplate = {
    trail: null,
    map: null,
    weather: null,
    hiking: false,
}